let products = [
    {
        id: 1,
        name: "Blouse",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 2,
        name: "Shirt",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 3,
        name: "Intimates",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 4,
        name: "Bodysuit",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 4,
    },
    {
        id: 5,
        name: "Corset",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 6,
        name: "Pashima",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 2,
    },
    {
        id: 7,
        name: "Sport wear",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 8,
        name: "Bra",
        category: "man",
        quantity: 1,
        stock: 10,
        sold: 1,
    },
    {
        id: 9,
        name: "Caftan",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 5,

    },
    {
        id: 10,
        name: "Shorts",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 9,
    },
    {
        id: 11,
        name: "Boots",
        category: "men",
        quantity: 1,
        stock: 15,
        sold: 6,
    },
    {
        id: 12,
        name: "Sweater",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,

    },
    {
        id: 13,
        name: "Skirt",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 4,
    },
    {
        id: 14,
        name: "Vest",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 4,
    },
    {
        id: 15,
        name: "Socks",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 16,
        name: "Cowl Neck Top",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 4,
    },
    {
        id: 17,
        name: "Jeans",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 4,
    },
    {
        id: 18,
        name: "Dress",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 2,
    },
    {
        id: 19,
        name: "Long coat",
        category: "men",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 20,
        name: "Full skirt dress",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 21,
        name: "A-line skirt",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 22,
        name: "Suit jacket",
        category: "man",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 23,
        name: "Polo shirt",
        category: "man",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 24,
        name: "Khakis",
        category: "man",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 25,
        name: "Henley Shirt",
        category: "man",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 26,
        name: "Blazer",
        category: "man",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 27,
        name: "T-shirt",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 28,
        name: "Jacket",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 29,
        name: "Hoddie",
        category: "man",
        quantity: 1,
        stock: 10,
        sold: 5,
    },
    {
        id: 30,
        name: "Frock",
        category: "woman",
        quantity: 1,
        stock: 10,
        sold: 5,
    },

]

function saveProducts() {

    localStorage.setItem("products",JSON.stringify(products)) // to add question to local storage by converting data to JSON format
  
}
saveProducts()

